GET http://localhost:3000
###Registrar un usuario
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
    "username":"alex",
    "email": "alexitotn21@gmail.com",
    "password": "123456"
}


###Iniciar sesión
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "username":"alex",
    "email": "alexdsfit2o@gmail.com",
    "password": "3242342"
}


###Crear un post 
POST http://localhost:3000/api/posts/create
Cookie:acces_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsZXgiLCJlbWFpbCI6ImFsZXhpbWVzQGdtYWlsLmNvbSIsImlhdCI6MTYxNjYwNjYwMn0.1J9Q6Q6J9Q6Q6J9

{
    "email_user":"angel@gmail.com",
    "post":"Hola este es mi primer post"
}

###Obtener todos los post
POST http://localhost:3000/api/posts/get
Content-Type: application/json

{
    "email_user":"angel@gmail.com"
}
